.changeset/clever-houses-heal.md
package-lock.json
packages/agents/package.json
packages/hono-agents/package.json

This improves a few minor things in the `package.json` of the packages, so https://www.npmjs.com/package/agents-sdk?activeTab=readme etc. link to the repo/folder, as well as the issue tracker.
I also updated the author/license for the `agents` package which seems correct with the rest of the repo, but pls yell if incorrect!

fix: add repo/bug tracker links to packages

---

.changeset/healthy-bananas-roll.md
packages/agents/src/ai-chat-agent.ts
packages/agents/src/ai-react.tsx
packages/agents/src/ai-types.ts
packages/agents/src/client.ts
packages/agents/src/index.ts
packages/agents/src/react.tsx

Used Claude 3.7 with the following prompt:
Generate valid JSDoc comments for the public types in the `agents` package.
Comments should be generated for all public types, including classes,
interfaces, and functions. Comments should include a description of the type,
its parameters, and its return value. Be concise, and do not include any
unnecessary details.
Return the entirety of each file separately, and include all other code, even
if there are no JSDOc comments for those symbols.

adds JSDoc to public symbols.

---

.changeset/slow-suits-agree.md
packages/hono-agents/README.md

From what I could tell from grepping the codebase and what worked for me, the leading slash is not supposed to be there.

Fix agents prefix in example

---

.changeset/stale-toys-protect.md
packages/agents/src/react.tsx

The commit updating the `cf_agent_state` logic added a bug where the user's `onMessage` would never get called for string messages.
https://github.com/cloudflare/agents/commit/b244068c7266f048493b3796393cfa74bbbd9ec1#diff-93607242176a99b6eb20508d9bb1707085a97ec316e8835d194d97fa6b44a04cL35-R40

fix onMessage not getting called

---

.changeset/deep-pumas-peel.md
examples/playground/src/agents/rpc.ts
examples/playground/src/client.tsx
examples/playground/src/components/RPC.css
examples/playground/src/components/RPC.tsx
examples/playground/src/server.ts
examples/playground/wrangler.jsonc
packages/agents/src/client.ts
packages/agents/src/index.ts
packages/agents/src/react.tsx
tsconfig.json

- Remote procedure calls from clients to agents
- Method decoration with `@unstable_callable` to expose agent methods
- Support for both regular and streaming RPC calls
- Type-safe RPC calls with automatic response handling
- Real-time streaming responses for long-running operations
Note: The `callable` decorator has been renamed to `unstable_callable` to indicate its experimental status.

Add RPC support with `unstable_callable` decorator for method exposure.

---

.changeset/thin-foxes-hang.md
packages/agents/src/ai-react.tsx

In current version I get an error 
`
Types of parameters state and state are incompatible.
`
When trying to type the `useAgent` hook with my state object. 
E.g.
```ts
// No errors here
const agent = useAgent<{ currentRecipe: Recipe | null }>({
host: 'http://localhost:8787',
agent: 'chat',
onStateUpdate: (state) => {
setCurrentRecipe(state.currentRecipe);
},
});
const {
messages: agentMessages,
input: agentInput,
handleInputChange: handleAgentInputChange,
handleSubmit: handleAgentSubmit,
addToolResult,
clearHistory,
} = useAgentChat({
// Error here, my `currentRecipe` shape does not match `unknown` since the generic isn't being passed through
agent,
maxSteps: 5,
});
```

Pass state generic through `useAgentChat`

---

.changeset/purple-vans-end.md
package-lock.json
packages/agents/package.json
packages/agents/src/lib/sseEdge.ts
packages/agents/src/mcp.ts

Slight conflict with how Agents run with how MCP servers work, which I think we can unify eventually.
But for this initial release, I've made McpAgent extend DurableObject directly, then include an internal #agent instance to provide:
- state
- initialState
- setState
- onStateUpdate
- sql
An McpAgent provides a static mount(path), which does its own session-based routing. This again could be unified with routeAgentRequest, but isn't yet.
Example usage:
```ts
import { McpAgent } from 'agents/mcp'
export class MyMCP extends McpAgent<Env, { counter: number }, {}> {
server = new McpServer({
name: 'Demo',
version: '1.0.0',
})
initialState = {
counter: 1,
}
async init() {
this.server.tool('getCounter', 'Get the current value of the counter', {}, async ({}) => {
return {
content: [{ type: …
```

First pass at adding an `McpAgent`

---

.changeset/lovely-tips-joke.md
packages/agents/src/mcp.ts

Fixes an issue where classes extending `McpAgent` cannot access typesafe `this.env`, since the DurableObject type is declared as `DurableObject<Env = unknown>`

fix: Pass Env param thru to DurableObject definition

---

.changeset/grumpy-buckets-lead.md
examples/playground/src/agents/email.ts
guides/human-in-the-loop/src/app.tsx
packages/agents/src/index.ts

Export the current agent, request, and connection from a shared context. Particularly useful for tool calls that might not have access to the current agent in their module scope.

`import {context} from 'agents';`

---

.changeset/curvy-months-matter.md
packages/agents/package.json
packages/agents/scripts/build.ts

Made @modelcontextprotocol/sdk an external dependency, and made build failures actually fail

Fixed the build error that was stripping `.js` files from NPM

---

.changeset/puny-cows-drop.md
packages/agents/src/mcp/index.ts

Fixes https://github.com/cloudflare/agents/issues/148
Could instead throw an error here and ask people to set this themselves. But having hard time seeing problematic case if we just made it work as people might expect, who aren't thinking about the `path` argument as something that gets fed into `URLPattern`?

Automatically change "/" path to "/*" in MCP server mount() method

---

packages/agents/src/index.ts
packages/agents/src/mcp/index.ts

Addresses https://github.com/cloudflare/agents/issues/157
There were a couple of issues here:
- We were managing the connections explicitly, but then deferring to PartyKit's Server class for a lot of things. This led to the `Cannot read properties of null (reading '__pk')` error. We resolve this by deferring to the Agent class' `fetch` implementation so it can manage the websocket connection for us.
- We were not passing the `initialState` to the `#agent`, and `initialState` is not available during the constructor. We can resolve this by re-creating the `#agent` in `onStart`
- As a side effect of letting PartyKit manage the connections, we get some more messages broadcast back to the original worker that are not JSONRPC messages. I've re-worked the code there so that it filters those out.

Fix the state issues

---

.changeset/brave-dodos-worry.md
packages/agents/src/react.tsx

I noticed on my end that the `agent` reference would get out of date when using the `call` method - this seems to fix things.

Fix: Missing agent dep in useCallback

---

.changeset/crazy-walls-give.md
examples/mcp-client/src/server.ts
packages/agents/scripts/build.ts
packages/agents/src/mcp/client-connection.ts
packages/agents/src/mcp/client.ts
packages/agents/src/mcp/do-oauth-client-provider.ts

Agents changes:
* Explicitly pass in the OAuthProvider (and require it to be an `AgentsOAuthClientProvider`)
* Fix error where client initialization fails if a server returns "Method not found" for capabilities it claimed to support. This is more common in the case of resource templates because there is no explicit resource template capability. Now we warn on servers not advertising their capabilities correctly instead of hard failing. (See #125)
Demo fixes:
* Fix problem in the demo where unauthenticated servers wouldn't cause the capabilities list to be refreshed
* Fix broken demo due to `this.name` not being set. Now the callback URL doesn't need to be passed into the `MCPClientManager` (See #125)
I double checked that the `DurableObjectOAuthClientProvider` still works on the free …

Fixes to MCP Client with authentication

---

.changeset/good-coins-repeat.md
packages/agents/src/mcp/index.ts

Following up from https://github.com/cloudflare/agents/pull/186
Adding these back emits these logs in tests:
```
workerd/io/worker.c++:1020: info: console warning; message = An event handler returned a promise that will be ignored. Event handlers should not have a return value and should not be async functions.
```
I'm not sure how to best resolve

Revert Promise.resolve in event handlers

---

.changeset/nasty-ties-jog.md
packages/agents/src/mcp/index.ts
packages/agents/src/tests/mcp-streamable-http.test.ts

Fixes an error introduced in https://github.com/cloudflare/agents/pull/186
The first the the Streamable worker does on an incoming request with a `sessionId` is ask the DO if it's been initialized. If it has not, then the DO has never received an initialize message, and we should reject it.
In the current version once a DO hibernates, this always returns `false`.
However, we're conflating two different types of "initialization" here:
- We call "init" on the `McpAgent` class to allow the user to define the `McpServer`
- There is an "initialization" message that is the first message the Streamable server receives
This fixes the issue by having an explicit `setInitialized()` method, and tracking the second kind of authentication in DO storage.
There was also an additional error with the …

Fix streamable hibernation issues

---

.changeset/ninety-lizards-doubt.md
packages/agents/src/index.ts
packages/agents/src/mcp/client.ts
packages/agents/src/mcp/index.ts

- Every Agent now has a default McpClientManager (this.mcp)
- This means you can now connect to an MCP server from inside an MCP server (!!!)
- You can convert McpClientManager tools to be compatible with AI SDK

Agent::mcp, McpClientManager::unstable_getAITools

---

.changeset/fuzzy-ads-matter.md
packages/agents/src/mcp/index.ts

An attempt at fixing https://github.com/cloudflare/agents/issues/210
No more red squiggles or `@ts-ignore` in our demo code!

Fix type error for McpAgent.fetch

---

.changeset/moody-nails-melt.md
packages/agents/src/mcp/index.ts

Generalizes `McpServer.server` to also support promises.
In `playwright-mcp`, [mcp server is created asynchronously](https://github.com/cloudflare/playwright-mcp/blob/b51e41a0c5c71fc48eb2018a0ccdd48b2d6f4d60/src/index.ts#L79) and it's not possible to pass it to McpAgent, so these changes are to provide support for asynchronously created servers.

Support server as promises in McpAgent

---

.changeset/strong-cougars-change.md
packages/agents/src/mcp/index.ts

Implementing [this Hono example](https://blog.cloudflare.com/streamable-http-mcp-servers-python/#streamable-http-a-simpler-way-for-ai-agents-to-communicate-with-services-via-mcp) will result in a [typescript-eslint's unbound-method](https://typescript-eslint.io/rules/unbound-method/) warning.
Since the `fetch` function returned by `MCPAgent.serve` and `MCPAgent.serveSSE` does not access `this`,
explicitly annotating `this` with `void` makes the implementation type-safer and will not cause warnings.

fix(types): explicitly annotate this with void to avoid unbound method warning

---

.changeset/chatty-schools-speak.md
packages/agents/package.json
packages/hono-agents/package.json

- Add top level default types to package.json for both modules
- Works in conjunction with explicit exports object
- This lets the NPM registry know that this project indeed does support TS.
Don't bother with changeset, when it happens it happens.

chore: add top level default types to package.json

---

.changeset/gorgeous-bears-beam.md
packages/agents/src/ai-react.tsx

Fixes  cloudflare/agents-starter#69 (tested locally) - big thank you to @Gyurmatag
***
So in https://github.com/cloudflare/agents/pull/105, I forgot to also close the controller after sending an abort signal. This meant the `isLoading` from the chat agent hook didn't turn back to false.

Ensure isLoading is false after you `stop` an ongoing chat agent request

---

.changeset/gorgeous-poems-care.md
packages/agents/src/index.ts

Since the Agent class has a custom implementation for scheduled tasks via `this.schedule`, if the `alarm` class is implemented on a subclass, it doesn't perform as expected. While a quick trip to the docs would point you in this direction, it would be nice to have a ts error and js doc explaining that instead of implementing alarm, use the schedule method instead. Was able to find a solution to provide a type warning in one case, but not sure if there is a better way to do this to catch all cases?
- Updates alarm function on Agent class to be readonly, to produce a ts error on subclasses trying to override this method as an instance member function
- Adds js doc to alarm function with link to schedule-task docs, in the hopes that this steers them in the right direction
- In the …

Update Agent.alarm to readonly, linking to schedule-task docs

---

.changeset/forty-eagles-worry.md
packages/agents/src/mcp/sse-edge.ts

This PR enhances SSEEdgeClientTransport to support custom fetch options and merges custom request headers with workerOptions headers.
In my use case, I was trying to pass along CF access id and secrets as headers to a remote mcp server but those headers were not sent because SSEEdgeClientTransport is overriding the fetch function and doesn't call user-provided fetch function when it exists.
1. Connect to an mcp server behind Cloudflare access using a clone of this branch.
```ts
manager.connect("https://mcp.example.com/sse", {
transport: {
eventSourceInit: {
fetch: (url, init) => fetch(url, {
...init,
headers: {
...init?.headers,
'CF-Access-Client-Id': env.CF_ACCESS_CLIENT_ID,
'CF-Access-Client-Secret': env.CF_ACCESS_CLIENT_SECRET
}
})
},
//requestInit: {
//headers: { …
```

fix: allow overriding fetch and request headers in SSEEdgeClientTransport

---

.changeset/popular-dingos-perform.md
biome.json
examples/mcp/src/server.ts
examples/playground/src/agents/chat.ts
examples/playground/src/agents/email.ts
guides/human-in-the-loop/src/server.ts
guides/human-in-the-loop/src/utils.ts
packages/agents/package.json
packages/agents/src/index.ts
packages/agents/src/react.tsx
packages/agents/src/tests-d/example.test-d.ts
packages/agents/src/tests-d/typed-use-agent.test-d.ts
packages/agents/src/tests-d/untyped-use-agent.test-d.ts
packages/agents/src/tests/wrangler.toml

Proposal to add type support to react useAgent() RPC calls. It can infer argument tyoes and ensure we pass all required values.
Usage example:
```ts
// server.ts
class MyAgent extends Agent<typeof env, {}> {
@callable()
sayHello(name?: string): string {
return `Hello, ${name ?? 'World'}!`;
}
@callable()
async perform(task: string, p1?: number): Promise<void> {
// do something
}
// not annotated with @callable()
nonRpc(): void {
}
}
// index.tsx
import type { MyAgent } from './server.ts';
// ...
const agent = useAgent<{}, MyAgent>({ agent: 'my-agent' });
// return type is promisified
agent.call('sayHello') satisfies Promise<string>;
// @ts-expect-error first argument is not a string
await agent.call('sayHello', [1]);
await agent.call('perform', ['some task', 1]);
await …
```

Add type support to react useAgent().call

---

.changeset/ninety-lizards-pay.md
packages/agents/src/react.tsx
packages/agents/src/tests-d/example-stub.test-d.ts
packages/agents/src/tests-d/use-agent-stub.test-d.ts

A proposal for a stub object for Agent RPC that better mimics method calls.
Usage example:
```ts
const { stub } = useAgent<MyAgent, {}>({ agent: "my-agent" });
// return type is promisified
stub.sayHello() satisfies Promise<string>;
// @ts-expect-error first argument is not a string
await stub.sayHello(1);
await stub.perform("some task", 1);
await stub.perform("another task");
// @ts-expect-error requires parameters
await stub.perform();
```

Stub for Agent RPC

---

.changeset/seven-shirts-decide.md
packages/agents/src/react.tsx
packages/agents/src/tests-d/untyped-use-agent-stub.test-d.ts
packages/agents/src/tests-d/use-agent-stub.test-d.ts

Stub intellisense was including base Agent methods:
I improved and simplified AgentStub type to fix it, and add a few more type tests.

Improve Agent stub

---

.changeset/public-spoons-return.md
packages/agents/src/react.tsx
packages/agents/src/tests-d/example-stub.test-d.ts
packages/agents/src/tests-d/example.test-d.ts
packages/agents/src/tests-d/typed-use-agent.test-d.ts
packages/agents/src/tests-d/untyped-use-agent-stub.test-d.ts
packages/agents/src/tests-d/untyped-use-agent.test-d.ts
packages/agents/src/tests-d/use-agent-stub.test-d.ts

I think this is the final version! Even if the previous version was passing the tests, I was not happy with those types because I couldn't understand why they were not behaving the way I expected them to.
For instance, `Methods<T>` should return a object type with only `Method`  values, something similar to `Record<string, Method>` but if I tried to use `Parameters<Method<T>[K]>` it would fail, which was odd.
It turns out I was missing a condition in the `Method<T>` value, even if its keys were already using the same condition.
After fixing that one and `OptionalAgentMethods`, which had the same problem, I was able to simplify the remaining types, like `AgentStub<T>` which no longer needs to be a `type AgentStub<T extends AgentMethods<T>>`.

Improve agent types

---

.changeset/gorgeous-donkeys-bake.md
packages/agents/package.json
packages/agents/src/client.ts
packages/agents/src/index.ts
packages/agents/src/react.tsx
packages/agents/src/serializable.ts
packages/agents/src/tests-d/example-stub.test-d.ts
packages/agents/src/tests-d/example.test-d.ts
packages/agents/src/tests-d/typed-use-agent.test-d.ts
packages/agents/src/tests-d/untyped-use-agent-stub.test-d.ts
packages/agents/src/tests-d/untyped-use-agent.test-d.ts
packages/agents/src/tests-d/use-agent-stub.test-d.ts

Last one (I guess...)!
In "typed" mode, onlly serializable parameters and return values or their promises are supported, so this is not retro-compatible with my previous changes.
However, I kept retro-compatibility with type-unsafe agent proxies.
Another breaking change is on `unstable_callable`, which enforces decorated method to be serializable.
I can revert those breaking changes, it's just a couple of lines.

Type-safe serializable RPC methods

---

.changeset/rude-glasses-know.md
packages/agents/src/mcp/client.ts

Resolves #284 
Simple one line fix to remove the orphaned MCP state after deleting a connection.

Fix issue where stray MCP connection state is left after closing connection

---

.changeset/modern-crabs-smash.md
packages/agents/src/mcp/index.ts

Introduced a type guard function `isDurableObjectNamespace` to validate objects as DurableObjectNamespace. Updated relevant checks in McpAgent to use this type guard for improved type safety and clarity.
Fixes #294

Add type guard for DurableObjectNamespace

---

.changeset/bumpy-doors-tap.md
examples/mcp-client/README.md
packages/agents/src/index.ts
packages/agents/src/mcp/client.ts

Context:
When the Agent DO wakes up (triggering its onStart function), it attempts to connect to all MCP servers it has previously configured for the client. This is great for servers that either don't require authentication or have previously been authenticated with a successful OAuth flow. 
Problem:
There is a problem, however, if the onStart function is triggered during the course of authenticating a server. It's a problem because the connection process generates a new auth url (specifically a new "code" within the authurl) for any servers still requiring authentication. If you're currently trying to authenticate a server and that authurl changes before the process completes, you get a token exchange error.
Solution:
Excluding these authenticating servers from potential connection …

FIX: Only attempt server connections with servers not actively in oauth flow

---

.changeset/bumpy-doors-tap.md

#299 had a minor changeset instead of a patch changeset. This fixes that.

Fix changeset

---

examples/mcp/README.md

MCP vs. Agent url mixup. Agent using port `5174`, as setup in `vite.config.ts`

MCP example: url mixup fix

---

examples/mcp/README.md

Sorry @threepointone, there was definitely a mixup but also in that last PR.
MCP server is running on 5174 in the example and should be removed I guess.
This lets it actually successfully run the example

MCP example url mixup number 2

---

.changeset/proud-groups-lick.md
packages/agents/src/mcp/index.ts

Follows on from https://github.com/cloudflare/agents/pull/261. The most recent version of the SDK `1.13.x` now sends a `mcp-protocol-version` header as part of the Client -> Server communication. This is blocked by CORS by default, so adding it to our default allowlist.
I have verified that `mcp-protocol-version` is never sent from the Server -> Client, so it doesn't need to be included in the `Access-Control-Expose-Headers` header, unlike `mcp-session-id`

Added mcp-protocol-version to CORS Access-Control-Allow-Headers

---

.changeset/chilly-owls-wonder.md
packages/agents/package.json
packages/agents/scripts/build.ts
packages/agents/src/ai-chat-agent.ts
packages/agents/src/index.ts
packages/agents/src/observability/index.ts

Adds a new `observability` property to Agents that receives events during the Agent's exeuction that can be used for configurable observability. The default observability implementation prints the events to console, but in the future this could be hooked up to a UI or some other observability tooling.

feat(obs): basic agent instrumentation

---

.changeset/puny-bikes-bow.md
packages/agents/src/index.ts

Prevents a single failure from causing all items in the queue from being retried (including previously processed items that were successful).

fix: dequeue items in DB after each task is complete

---

.changeset/sharp-eyes-buy.md
packages/agents/src/mcp/client-connection.ts
packages/agents/src/tests/mcp/client-connection.test.ts

Small change kinda addressing #320 
Instead of failing the connection this would provide a fallback and log the error that registering a capability failed.
Another alternative would be:
- `try..catch` on the `Promise.all`
-  mark the `this.connectionState = failed` and exit the function
Changes:
- Replace Promise.all with Promise.allSettled in MCP client initialization to handle partial capability failures gracefully
- Log failed capabilities instead of throwing errors that break entire connections

Improve MCP client connection resilience with Promise.allSettled

---

.changeset/swift-moments-care.md
packages/agents/README.md
packages/agents/src/mcp/client-connection.ts
packages/agents/src/mcp/index.ts
packages/agents/src/tests/mcp/transports/auto.test.ts
packages/agents/src/tests/shared/test-utils.ts
packages/agents/src/tests/worker.ts

Resolves https://github.com/cloudflare/agents/issues/367

feat: add auto transport for client

---

.changeset/swift-feet-sleep.md
packages/agents/src/index.ts
packages/agents/src/tests/msg-ordering.test.ts
packages/agents/src/tests/server/ordering.test.ts
packages/agents/src/tests/worker.ts
packages/agents/src/tests/wrangler.jsonc

Fixes #321 and adds test for message ordering.

Fix onConnect race condition

---

.changeset/hot-dogs-camp.md
packages/agents/src/mcp/utils.ts

Since we're closing response writers in event handlers, we can't reliably know which one will run first and might try to close the same one twice. This PR simply makes them fail silently.
We only need to update Streamable HTTP handlers since SSE was already doing this.
Addresses #456

Silently handle writer close errors

---

.changeset/plain-pigs-lead.md
packages/agents/src/ai-chat-agent.ts

The finalized message will now also include the final reasoning text.
In general one should consider if this part of the agent sdk shouldn't be reworked (a lot) because the current generation of reasoning models (Claude 4, GPT-5 and Grok 4) reason a little, call a tool and then continue to reason. I think this should also be persistet so people don't get confused. The ai-sdk probably already includes some code for this kind of persistence. Maybe the agent-sdk should just use that instead of rolling it's own.

feat: Include reasoning text in finalized message

---

.changeset/polite-oranges-pretend.md
packages/agents/src/mcp/utils.ts
packages/agents/src/tests/shared/test-utils.ts

In the Streamable HTTP handler we were reading the session ID from query parameters instead of the proper header.
That was the case for SSE but not for Streamable HTTP.

use header for session ids in streamable http GET streams

---

.changeset/good-coats-poke.md
packages/agents/src/mcp/index.ts
packages/agents/src/mcp/utils.ts

The MCP TS SDK's Server [sets the client information](https://github.com/modelcontextprotocol/typescript-sdk/blob/main/src/server/index.ts#L295-L296) when dealing with an `InitializeRequest` in memory.
This makes it so that IF an `McpAgent` hibernates or is evicted when already initialized, this data (e.g. `this.server.server.getClientCapabilities()`) will no longer be available since clients won't try to initialize again.
Since we were already storing a boolean to signal whether the `McpAgent` was initialized (only used internally, so I think it's OK to update this), we can store the `InitializeRequest` instead and send it on every startup when present, so `this.server` always has the data available.
~PS:  Also updated the methods to use the new KV sync API~

Store initialize requests and set them in onStart

---

guides/human-in-the-loop/src/server.ts
packages/agents/src/ai-react.tsx

fixes #477 
- added stopWhen: stepCountIs(5) for more than 2 steps prompts 
- for more than one confirmation added a function in ai-react to wait until there are no pending confirmations and only then send messages

add step count limit and auto-send control for tool confirmations

---

.changeset/tender-suns-decide.md
packages/agents/src/ai-types.ts
packages/agents/src/mcp/index.ts
packages/agents/src/mcp/transport.ts
packages/agents/src/mcp/utils.ts
tsconfig.base.json

Refactor the custom Streamable HTTP transport to closely match the behavior of the [MCP SDK's implementation](https://github.com/modelcontextprotocol/typescript-sdk/blob/main/src/server/streamableHttp.ts)
This also updates how we bridge from the Worker to the transport within the agent.
**PREVIOUSLY**:
- The `McpAgent.serve(...)` handler in the Worker would get a POST request, read the body and make sure it was a valid JSON-RPC message and apply validation per the spec. (this we keep)
- Then, it would establish a WebSocket to the `McpAgent`, forward the JSON-RPC payloads over WS, keep a requestId -> connectionId map, send a private `cf/standalone_sse/attach` notif to bind the “standalone SSE stream” ([this](https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#listening …

Refactor streamable HTTP transport

---

.changeset/yellow-owls-report.md
examples/mcp-client/src/server.ts
packages/agents/src/core/events.ts
packages/agents/src/index.ts
packages/agents/src/mcp/client-connection.ts
packages/agents/src/mcp/client.ts
packages/agents/src/mcp/do-oauth-client-provider.ts
packages/agents/src/mcp/errors.ts
packages/agents/src/mcp/index.ts
packages/agents/src/observability/agent.ts
packages/agents/src/observability/base.ts
packages/agents/src/observability/index.ts
packages/agents/src/observability/mcp.ts
packages/agents/src/tests/mcp/client-connection.test.ts
packages/agents/src/tests/mcp/client-manager.test.ts
packages/agents/src/tests/mcp/transports/auto.test.ts

OAuth and transport selection were tightly coupled, causing authorization codes to be consumed during transport fallback attempts. This led to "authorization code already used" errors and made OAuth-protected MCP servers unusable.
Split the OAuth flow into two distinct phases:
1. **OAuth completion** - Finishes auth and probes for working transport
2. **Connection establishment** - Connects using the appropriate transport
- Remove transport tracking from OAuth provider (no longer needed)
- Add `finishAuthProbe()` to complete OAuth independently
- Allow transport type configuration in `addMcpServer()` options
- Add configurable OAuth callback handling (redirects, custom handlers)
- Fix callback URL persistence across Durable Object hibernation
- Add error helpers and logging for debugging …

Decouple OAuth authorization from transport selection

---

.changeset/flat-yaks-sing.md
packages/agents/src/ai-react.tsx

Remove `isToolCallInProgress` which wasn't being used for anything besides gating whether or not to close the stream. Leftover from some of the big changes, most likely.

remove isToolCallInProgress
